import re
from typing import Optional


INTENT_PATTERNS = {
    "community_need": [
        r"most common health issues",
        r"health issues",
        r"mental health (indicators|signals).*(increase|decrease|trend)",
        r"behavioral health",
        r"chronic disease",
        r"public health indicators",
        r"community need",
    ],
    "mental_health_needs": [
        r"largest mental health needs",
        r"biggest mental health needs",
        r"mental health needs in zip",
        r"mental health burden",
        r"mental health indicators",
        r"mental health data",
        r"depression.*distress",
        r"mental health.*78207",
    ],
    "housing_concentration": [
        r"housing issues? concentrated",
        r"housing problems? concentrated",
        r"housing.*specific neighborhoods",
        r"housing.*neighborhoods.*78207",
        r"housing issues.*78207",
        r"concentrated.*housing",
    ],
    "sdh_comprehensive": [
        r"social determinants? of health",
        r"every category.*social determinant",
        r"all categories.*social determinant",
        r"social determinant.*every category",
        r"sdoh|sdh",
        r"determinants of health.*all",
    ],
    "funding_decision": [
        r"improve decision.making.*funding",
        r"decision.making.*future funding",
        r"future funding.*decision",
        r"invest.*right services",
        r"funding.*address.*needs",
        r"how can we.*funding.*services",
    ],
    "connect_needs_services": [
        r"connect.*needs.*services.*funding",
        r"needs addressed.*services.*funding",
        r"link.*needs.*services",
        r"connect.*services provided.*funding",
        r"needs.*services.*decisions",
    ],
    "critical_issues": [
        r"most critical issues",
        r"critical issues affecting residents",
        r"biggest challenges.*residents",
        r"top issues.*78207",
        r"priority issues",
    ],
    "hyperlocal_assessment": [
        r"hyperlocal",
        r"community needs assessment",
        r"replicated citywide",
        r"build.*assessment.*78207",
        r"needs assessment.*78207",
    ],
    "underserved": [
        r"underserved.*based on.*data",
        r"which communities.*underserved",
        r"underserved communities",
        r"most underserved",
    ],
    "community_conditions_311": [
        r"housing[- ]related complaints",
        r"mold|pests?|sanitation",
        r"environmental hazards?",
        r"311",
        r"community distress",
        r"unsafe housing",
        r"noise complaints?",
    ],
    "service_landscape": [
        r"what .*services.*available",
        r"mental health services",
        r"behavioral health providers",
        r"organizations.*(youth|housing|mental)",
        r"fewer services",
        r"service coverage",
        r"service landscape",
    ],
    "need_service_gap": [
        r"need.*service.*gap",
        r"gaps?.*between.*resources.*demand",
        r"needs highest but services",
        r"largest service gaps?",
        r"not matched by service",
        r"high need.*limited services",
        r"underfunded relative to impact",
        r"demand.*high.*access.*limited",
        r"demand.*services.*high.*access",
        r"gaps?.*available resources",
        r"gaps?.*community demand",
    ],
    "funding_intelligence": [
        r"funding",
        r"investment",
        r"funded organizations?",
        r"funding gaps?",
        r"philanthropic",
        r"who funds what",
        r"funding opportunity",
        r"bond",
        r"interventions?",
        r"prioritize(d)? for funding",
        r"consumer spending",
        r"spending profile",
        r"market potential",
        r"health.*beauty.*market",
        r"beauty.*market",
        r"market.*health.*service",
        r"spending.*78207",
        r"economic.*market",
        r"market.*potential",
    ],
    "context_demographics": [
        r"demographics?",
        r"poverty rate",
        r"income distribution",
        r"income.*78207",
        r"lack health insurance",
        r"insurance coverage",
        r"social determinants",
        r"age distribution",
        r"race|ethnicity",
        r"economic profile",
        r"economic.*zip",
        r"zip.*economic",
        r"resident.*income",
        r"income.*resident",
    ],
    "community_need": [
        r"most common health issues",
        r"health issues",
        r"mental health (indicators|signals).*(increase|decrease|trend)",
        r"behavioral health",
        r"chronic disease",
        r"public health indicators",
        r"community need",
        r"community profile",
        r"overall.*profile.*78207",
        r"profile.*78207",
        r"sacrd",
        r"community data.*78207",
        r"medical care.*spend",
        r"spend.*medical",
        r"residents.*spend",
        r"what.*residents.*78207",
    ],
    "missing_sensitive_data": [
        r"\ber visits?\b",
        r"crisis response",
        r"substance use",
        r"overdose",
        r"suicide attempts?",
    ],
}


def detect_intent(prompt: str) -> Optional[str]:
    prompt_lower = prompt.lower()
    priority_order = [
        "missing_sensitive_data",
        "housing_concentration",
        "funding_decision",
        "sdh_comprehensive",
        "connect_needs_services",
        "critical_issues",
        "hyperlocal_assessment",
        "underserved",
        "mental_health_needs",
        "need_service_gap",
        "community_conditions_311",
        "service_landscape",
        "funding_intelligence",
        "context_demographics",
        "community_need",
    ]
    for intent_name in priority_order:
        patterns = INTENT_PATTERNS.get(intent_name, [])
        for pattern in patterns:
            if re.search(pattern, prompt_lower):
                return intent_name
    return None
